### ISSUE TITLE
Any issues to work on?

### ISSUE THREAD

**Issue by surfertas** [piquette/quantlib#1]
Apologies for opening an issue for this. Is this repo still being actively worked on? What areas needs work?

**Comment by ackleymi** [comment]
Hi, it is active. I'm having trouble deciding how I would like to architect the superstructure of the project. I'd like the crates and modules to fit together in a very cohesive and rust-canonical fashion, while also feeling familiar to users of the original quantlib. I cant seem to find examples in the rust community of projects of similar scope that accomplish this. Also, flattening the large class-inheritance structures of the original library into rust paradigms, while maintaining the mathematical extendibility of the original library, and cramming all that into a codebase that is manageable, is proving challenging to think about. Let me know if you have any thoughts - happy to hear some ideas.

**Comment by surfertas** [comment]
Thanks for the response will take the discussion to the Discussions forum, and close this issue!
